### ISSUE TITLE
请问pod install出错 怎么办

### ISSUE THREAD

**Issue by su350380433** [ModularizationDemo/OldProject#1]
[!] Unable to add a source with url `git@github.com:ModularizationDemo/PodSpec.git` named `modularizationdemo`.
(/usr/bin/git clone git@github.com:ModularizationDemo/PodSpec.git modularizationdemo

Cloning into 'modularizationdemo'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
)
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

**Comment by CodeWeaver13** [comment]
你的电脑没有添加github的公钥

**Comment by su350380433** [comment]
菜鸟一个，O(∩_∩)O谢谢
