### ISSUE TITLE
大神求指教HTTP 417 

### ISSUE THREAD

**Issue by su350380433** [ModularizationDemo/OldProject#2]
pod repo push PrivatePods --allow-warnings
在公司内网创建cocoapod私有库，报下面的错误，公司是在RhodeCode上搭建代码管理的

  - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone http://username@10.10.16.86:5000/ios/library/Lothar /var/folders/92/km3f2hrn3ss1m4r5_kxjs7n80000gn/T/d20170622-555-l6zkn --template= --single-branch --depth 1 --branch 1

Cloning into '/var/folders/92/km3f2hrn3ss1m4r5_kxjs7n80000gn/T/d20170622-555-l6zkn'...
error: RPC failed; HTTP 417 curl 22 The requested URL returned error: 417 Expectation Failed
fatal: The remote end hung up unexpectedly
) during validation.

跪谢大神👻

**Comment by CodeWeaver13** [comment]
检查一下ssh公钥是否添加到了git仓库管理内

**Comment by su350380433** [comment]
大神秒回😆
RhodeCode 内网搭架的没看到有ssh公钥的设置项啊

**Comment by CodeWeaver13** [comment]
我对RhodeCode不太熟悉，Github、Gitlab、Gogs都是可以添加SSH公钥的，这个错误一般是权限问题。你可以问一下你们的运维同学

**Comment by su350380433** [comment]
好的，再次感谢大神

**Comment by su350380433** [comment]
可能我们部署的代码管理库有bug吧，用spec.source  用 :commit =>就可以了，:tag =>死活就不行
